services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P@ssw0rd123!Secure"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
volumes:
  sql-data:

# services:
#   sql:
#     image: mcr.microsoft.com/mssql/server:2022-latest
#     container_name: sql
#     environment:
#       ACCEPT_EUA: "1"
#       MSSQ_SA_PASSWORD: "Password@1"
#     ports:
#       - "1433:1433"